/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.record.BankTransactionRepository;
import org.example.record.Transaction;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class App {
	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}

    @Bean
	public CommandLineRunner run(BankTransactionRepository bankTransacRepository) {
		return args -> {
            System.out.println("transac1:");
			Transaction result = bankTransacRepository.findByTransactionId("9cfd2916-90b3-4965-8a7d-3f4043e4f583");
			
			System.out.println("transac2:" + result);

            result = bankTransacRepository.findTransactionIdUsingJPQL("9cfd2916-90b3-4965-8a7d-3f4043e4f583");
			
			System.out.println("transac3:" + result);
		};
	}
}
