CREATE TABLE BANK_TRANSACTION(
  TRANSACTION_ID UUID PRIMARY KEY,
  DATETIME TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR NOT NULL,
  AMOUNT NUMERIC(12,2) NOT NULL,
  TRANSACTION_TYPE VARCHAR(5) NOT NULL
);