/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

import org.example.record.BankTransactionRepository;
import org.example.record.Transaction;
import org.example.record.TransactionType;

@DataJpaTest
class AppTest {
    @Autowired
    private BankTransactionRepository bankTransacRepository;

    @Test
    void testRecordImpl() {
        System.out.println("transac1:");
        Transaction result = bankTransacRepository.findByTransactionId("9cfd2916-90b3-4965-8a7d-3f4043e4f583");

        System.out.println("transac2:" + result);

        result = bankTransacRepository.findTransactionIdUsingJPQL("9cfd2916-90b3-4965-8a7d-3f4043e4f583");

        System.out.println("transac3:" + result);
    }

    @Test
    void testFetchAll() {
        System.out.println("purchases:");
        List<Transaction> result = bankTransacRepository.fetchAll(TransactionType.DebitCardPurchase);
        System.out.println(result);
    }
}
